# This configuration file is used by the service LGTM
#
# Doc
# https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#language_block
# https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html#configure

extraction:
  cpp:
    prepare:
      packages: 
        - mpich
        - libmpich-dev 
        - libhdf5-mpich-dev
    after_prepare: "export HDF5_ROOT_DIR=/usr/lib/x86_64-linux-gnu/hdf5/mpich/"
    before_index: "export HDF5_ROOT_DIR=/usr/lib/x86_64-linux-gnu/hdf5/mpich/"
    index:
      build_command:
        - make -j 2

